export const ON_SAVE_CHART_BLOCK ="ON_SAVE_CHART_BLOCK"
export const ON_SHOW_CHART_CONFIG ="ON_SHOW_CHART_CONFIG"
export const ON_SAVE_LIST_CHART_STRING = "ON_SAVE_LIST_CHART_STRING"
export const ON_SAVE_LIST_CHART_BLOCK = "ON_SAVE_LIST_CHART_BLOCK"